spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect

  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

#  cloud:
#    azure:
#      storage:
#        account: ${STORAGE_NAME}
#        endpoint: ${END-POINT}
#        sas-token: ${SAS_TOKEN}

application:
  jwt:
    secretKey: ${TOKEN_SECRET_KEY}
    accessExpiration: ${ACCESS_EXPIRE}
    refreshExpiration: ${REFRESH_EXPIRE}

server:
  port: 8080
