spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect

  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

  azure:
    storage:
      connection-string: ${STORAGE_CONNECT}
      container-name: ${STORAGE_CONTAINER}

application:
  jwt:
    secretKey: ${TOKEN_SECRET_KEY}
    accessExpiration: ${ACCESS_EXPIRE}
    refreshExpiration: ${REFRESH_EXPIRE}

openai:
  key: 04a2335b-bdd1-4d53-8544-a79d1940f9f7

server:
  port: 8080